
# This is a file for you to write an un-named queries. 
# Only one un-named query is allowed per file.
query {
  articleAnalyses{
    article {
      title
      date
      source
      link
      authors
    }
    summary
    climate
  }
}